In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
df = pd.read_csv("/content/student_performance_dirty.csv")
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index,Notes
0,7.0,99,Yes,9.0,1,91.0,excellent
1,4.0,82,No,4.0,2,65.0,review
2,8.0,51,Yes,7.0,2,45.0,review
3,5.0,52,Yes,5.0,2,36.0,excellent
4,7.0,75,No,8.0,5,66.0,review

In [3]:
print("Shape of dataset:", df.shape)
print("\nColumn names:")
print(df.columns)

Shape of dataset: (10005, 7)

Column names:
Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index',
       'Notes'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10005 entries, 0 to 10004
Data columns (total 7 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     8973 non-null   float64
 1   Previous Scores                   10005 non-null  int64
 2   Extracurricular Activities        10005 non-null  object
 3   Sleep Hours                       9509 non-null   float64
 4   Sample Question Papers Practiced  10005 non-null  int64
 5   Performance Index                 10005 non-null  float64
 6   Notes                             10005 non-null  object
dtypes: float64(3), int64(2), object(2)
memory usage: 547.3+ KB

In [5]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,8973.000000,10005.000000,9509.000000,10005.000000,10005.000000
mean,4.997325,69.437581,6.529078,4.590205,55.215792
std,2.590449,17.343872,1.696752,2.892721,19.213705
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,27.000000,100.000000

In [6]:
df.isnull().sum()

Hours Studied                       1032
Previous Scores                        0
Extracurricular Activities             0
Sleep Hours                          496
Sample Question Papers Practiced       0
Performance Index                      0
Notes                                  0
dtype: int64

In [9]:
df["Hours Studied"] = df["Hours Studied"].fillna(df["Hours Studied"].mean())
df["Sleep Hours"] = df["Sleep Hours"].fillna(df["Sleep Hours"].mean())

In [10]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
Notes                               0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(51)

In [13]:
df = df.drop_duplicates()

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
print(df.dtypes)

Hours Studied                       float64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                         float64
Sample Question Papers Practiced      int64
Performance Index                   float64
Notes                                object
dtype: object

In [16]:
le = LabelEncoder()

df["Extracurricular Activities"] = le.fit_transform(
    df["Extracurricular Activities"]
)

df["Notes"] = le.fit_transform(
    df["Notes"]
)

In [17]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index,Notes
0,7.0,99,1,9.0,1,91.0,0
1,4.0,82,0,4.0,2,65.0,1
2,8.0,51,1,7.0,2,45.0,1
3,5.0,52,1,5.0,2,36.0,0
4,7.0,75,0,8.0,5,66.0,1

In [20]:
print(df.columns.tolist())

['Hours Studied', 'Previous Scores', 'Extracurricular Activities', 'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index', 'Notes']

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numerical_columns = [
    "Hours Studied",
    "Previous Scores",
    "Sleep Hours",
    "Sample Question Papers Practiced"
]

df[numerical_columns] = scaler.fit_transform(
    df[numerical_columns]
)

df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index,Notes
0,0.817086,1.704356,1,1.476834,-1.241351,1.862572,0
1,-0.405963,0.724104,0,-1.539252,-0.895533,0.509269,1
2,1.224768,-1.063414,1,0.270399,-0.895533,-0.531733,1
3,0.001720,-1.005752,1,-0.936035,-0.895533,-1.000184,0
4,0.817086,0.320471,0,0.873616,0.141919,0.561319,1

In [23]:
print("Final Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Final Shape: (9954, 7)

Missing Values:
Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
Notes                               0
dtype: int64

Duplicate Rows:
0

Data Types:
Hours Studied                       float64
Previous Scores                     float64
Extracurricular Activities            int64
Sleep Hours                         float64
Sample Question Papers Practiced    float64
Performance Index                   float64
Notes                                 int64
dtype: object

In [24]:
df.to_csv("student_preprocessed.csv", index=False)